ALTER TABLE "Session"
  ADD COLUMN "authMethod" TEXT NOT NULL DEFAULT 'PASSWORD',
  ADD COLUMN "mfaVerifiedAt" TIMESTAMP(3);

ALTER TABLE "RefreshToken"
  ADD COLUMN "authMethod" TEXT NOT NULL DEFAULT 'PASSWORD',
  ADD COLUMN "mfaVerifiedAt" TIMESTAMP(3);
